In [58]:
import pandas as pd

dubai_crude = pd.read_csv("c:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/data/oil rates/Dubai Crude.csv")

In [59]:
dubai_crude.head(5)

         Date  Price   Open   High    Low Vol. Change %
0  20-12-2024  72.79  72.79  72.79  72.79  NaN    0.04%
1  19-12-2024  72.76  72.76  72.76  72.76  NaN   -0.24%
2  18-12-2024  72.94  72.94  72.94  72.94  NaN    0.12%
3  17-12-2024  72.85  72.85  72.85  72.85  NaN   -0.38%
4  16-12-2024  73.13  73.13  73.13  73.13  NaN   -0.38%

In [60]:
dubai_crude.drop(columns=["Open", "High", "Low", "Vol.", "Change %"], inplace=True)
dubai_crude.head(5)

         Date  Price
0  20-12-2024  72.79
1  19-12-2024  72.76
2  18-12-2024  72.94
3  17-12-2024  72.85
4  16-12-2024  73.13

In [61]:
dubai_crude.index = dubai_crude.index + 1

dubai_crude.head(5)

         Date  Price
1  20-12-2024  72.79
2  19-12-2024  72.76
3  18-12-2024  72.94
4  17-12-2024  72.85
5  16-12-2024  73.13

In [62]:
dubai_crude = dubai_crude.iloc[::-1].reset_index(drop=True)
dubai_crude.head(5)

         Date  Price
0  28-04-2014  104.0
1  29-04-2014  104.0
2  30-04-2014  104.0
3  01-05-2014  104.0
4  02-05-2014  104.0

In [63]:
dubai_crude.index = dubai_crude.index + 1
dubai_crude.head(5)

         Date  Price
1  28-04-2014  104.0
2  29-04-2014  104.0
3  30-04-2014  104.0
4  01-05-2014  104.0
5  02-05-2014  104.0

In [64]:
dubai_crude.to_csv("c:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/data/oil rates/updated_Dubai_Crude.csv")

Data cleaning of WTI

In [65]:
wti = pd.read_csv("c:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/data/oil rates/wti.csv")
wti.head(10)

         Date  USD CAD oil prices(dollars)
0  2014-01-01                          NaN
1  2014-01-02                        95.14
2  2014-01-03                        93.66
3  2014-01-06                        93.12
4  2014-01-07                        93.31
5  2014-01-08                        91.90
6  2014-01-09                        91.36
7  2014-01-10                        92.39
8  2014-01-13                        91.45
9  2014-01-14                        92.15

In [66]:
wti.isna().value_counts()

Date   USD CAD oil prices(dollars)
False  False                          2764
       True                            115
Name: count, dtype: int64

In [67]:
wti['USD CAD oil prices(dollars)'] = wti['USD CAD oil prices(dollars)'].interpolate()
wti.head(50)

          Date  USD CAD oil prices(dollars)
0   2014-01-01                          NaN
1   2014-01-02                       95.140
2   2014-01-03                       93.660
3   2014-01-06                       93.120
4   2014-01-07                       93.310
5   2014-01-08                       91.900
6   2014-01-09                       91.360
7   2014-01-10                       92.390
8   2014-01-13                       91.450
9   2014-01-14                       92.150
10  2014-01-15                       93.780
11  2014-01-16                       93.540
12  2014-01-17                       93.960
13  2014-01-20                       94.235
14  2014-01-21                       94.510
15  2014-01-22                       96.350
16  2014-01-23                       97.230
17  2014-01-24                       96.660
18  2014-01-27                       95.820
19  2014-01-28                       97.490
20  2014-01-29                       97.340
21  2014-01-30                       98.250
22  2014-01-31                       97.550
23  2014-02-03                       96.440
24  2014-02-04                       97.240
25  2014-02-05                       97.400
26  2014-02-06                       97.840
27  2014-02-07                       99.980
28  2014-02-10                      100.120
29  2014-02-11                       99.960
30  2014-02-12                      100.380
31  2014-02-13                      100.270
32  2014-02-14                      100.310
33  2014-02-17                      101.425
34  2014-02-18                      102.540
35  2014-02-19                      103.460
36  2014-02-20                      103.200
37  2014-02-21                      102.530
38  2014-02-24                      103.170
39  2014-02-25                      102.200
40  2014-02-26                      102.930
41  2014-02-27                      102.680
42  2014-02-28                      102.880
43  2014-03-03                      105.340
44  2014-03-04                      103.640
45  2014-03-05                      101.750
46  2014-03-06                      101.820
47  2014-03-07                      102.820
48  2014-03-10                      101.390
49  2014-03-11                      100.290

In [68]:
wti.isna().value_counts()

Date   USD CAD oil prices(dollars)
False  False                          2878
       True                              1
Name: count, dtype: int64

In [69]:
wti = wti.fillna(wti['USD CAD oil prices(dollars)'].mean())

In [70]:
wti.index = wti.index + 1
wti.head(10)

          Date  USD CAD oil prices(dollars)
1   2014-01-01                     64.93763
2   2014-01-02                     95.14000
3   2014-01-03                     93.66000
4   2014-01-06                     93.12000
5   2014-01-07                     93.31000
6   2014-01-08                     91.90000
7   2014-01-09                     91.36000
8   2014-01-10                     92.39000
9   2014-01-13                     91.45000
10  2014-01-14                     92.15000

In [71]:
wti.to_csv("c:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/data/oil rates/updated_wti.csv")

Data Cleaning for Brent

In [73]:
brent = pd.read_csv("c:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/data/oil rates/brent.csv")
brent.head(5)

         Date  EUR GBP OIL Rate(dollars)
0  2014-01-01                        NaN
1  2014-01-02                     107.94
2  2014-01-03                     106.57
3  2014-01-06                     106.71
4  2014-01-07                     107.01

In [77]:
brent['EUR GBP OIL Rate(dollars)'] = brent['EUR GBP OIL Rate(dollars)'].interpolate()

In [80]:
brent = brent.fillna(brent['EUR GBP OIL Rate(dollars)'].mean())

In [81]:
brent.index = brent.index + 1
brent.head(5)

         Date  EUR GBP OIL Rate(dollars)
1  2014-01-01                  69.128664
2  2014-01-02                 107.940000
3  2014-01-03                 106.570000
4  2014-01-06                 106.710000
5  2014-01-07                 107.010000

In [82]:
brent.to_csv("c:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/data/oil rates/updated_brent.csv")